version: '3.8'
services:
  postgres:
    image: postgres:18
    container_name: postgres-slack
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slack_db
    ports:
      - "5438:5432"
    volumes:
      - ./docker/db/postgresql:/var/lib/postgresql/18/docker
